site_name: '语涵编译器'
docs_dir: 'docs'
site_dir: 'generated'

theme:
  name: 'material'
  palette:
    primary: cyan
  language: 'zh'


markdown_extensions:
  - attr_list:
  - admonition:
  - pymdownx.details:
  - pymdownx.superfences: # 添加 mermaid 支持，用来画图
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          default: true
          name: 简体中文
          site_name: 语涵编译器
          nav_translations:
            indexpage: 首页
            quickstart: 快速上手样例
            intro: 简介
            frontend: 剧本格式（前端）
            frontendcmddocs: 命令列表（自动生成）
            assetlistings: 内嵌素材列表（自动生成）
            middleend: 分析优化工具（中端）
            backend: 引擎支持（后端）
        - locale: zh-Hant
          name: 繁體中文
          site_name: 語涵編譯器
          nav_translations:
            indexpage: 首頁
            quickstart: 快速上手範例
            intro: 簡介
            frontend: 劇本格式（前端）
            frontendcmddocs: 命令列表（自動生成）
            assetlistings: 內嵌素材列表（自動生成）
            middleend: 分析優化工具（中端）
            backend: 引擎支持（後端）
        - locale: en
          name: English
          site_name: PrepPipe Compiler
          nav_translations:
            indexpage: Home
            quickstart: Quickstart Examples
            intro: Introduction
            frontend: Script Format (Frontend)
            frontendcmddocs: Commands Listing (Auto-generated)
            assetlistings: Embedded Assets Listing (Auto-generated)
            middleend: Analysis and Opt Tools (Middleend)
            backend: Engine Support (Backend)
  - privacy
  - offline
  # 中文搜索目前效果不好，不过 ezlinks 插件需要该项
  - search
  - ezlinks

  # - mkdocs-pdf

  # git-revision-date-localized 需要
  # 等这个插件支持 locale 字符串长于两个字母时再启用，现在 zh-Hant 会报错
  # - git-revision-date-localized:
  #    type: iso_date


nav:
  - indexpage: 'index.md'
  - quickstart:
    - "quickstart/pipeline.md"
  - intro:
    - "intro/why_preppipe.md"
    - "intro/usage.md"
    - "intro/functionality.md"
  - frontend:
    - "script/overview.md"
    - frontendcmddocs: "script/cmddocs.md"
    - assetlistings: "generated/script/assets.md"
  - middleend:
    - "middleend/overview.md"
    - "middleend/assetusage.md"
  - backend:
    - "engine/renpy.md"
    - "engine/webgal.md"

