site_name: '语涵编译器'
docs_dir: 'docs'
site_dir: 'generated'

theme:
  name: 'material'
  palette:
    primary: cyan
  language: 'zh'

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: zh
          default: true
          name: 简体中文
          site_name: 语涵编译器
        - locale: zh-Hant
          name: 繁體中文
          site_name: 語涵編譯器
        - locale: en
          name: English
          site_name: PrepPipe Compiler
  - privacy
  - offline
  # git-revision-date-localized 需要 search 插件支持
  # 中文搜索目前效果不好，暂时禁用
  # - search
  # 等这个插件支持 locale 字符串长于两个字母时再启用，现在 zh-Hant 会报错
  # - git-revision-date-localized:
  #    type: iso_date


nav:
  - 'index.md'
  - 'getting_started.md'
  - 'documentation.md'
